version: "3"

services:
  server:
    container_name: server
    platform: linux/amd64
    image: hxxn/omd:backend_ssl
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: "always"
    env_file:
      - .env
    networks:
      - omd

  web:
    container_name: web
    platform: linux/amd64
    image: hxxn/omd:web
    expose:
      - 5173
    ports:
      - 5173:5173
    networks:
      - omd

  nginx:
    container_name: nginx
    platform: linux/amd64
    restart: unless-stopped
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/nginx/conf.d:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - "server"
      - "web"
    networks:
      - omd
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    networks:
      - omd
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  omd:
    driver: bridge
